//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ACG.ONP.SIM.Domain.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "16.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class EnumResources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal EnumResources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("ACG.ONP.SIM.Domain.Resources.EnumResources", typeof(EnumResources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document généré.
        /// </summary>
        internal static string DocumentSpec_AutoGenerated {
            get {
                return ResourceManager.GetString("DocumentSpec_AutoGenerated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face derrière.
        /// </summary>
        internal static string DocumentSpec_Back {
            get {
                return ResourceManager.GetString("DocumentSpec_Back", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face derrière-gauche.
        /// </summary>
        internal static string DocumentSpec_BackLeft {
            get {
                return ResourceManager.GetString("DocumentSpec_BackLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face derrière-droite.
        /// </summary>
        internal static string DocumentSpec_BackRight {
            get {
                return ResourceManager.GetString("DocumentSpec_BackRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Tableau de bord.
        /// </summary>
        internal static string DocumentSpec_Dashboard {
            get {
                return ResourceManager.GetString("DocumentSpec_Dashboard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face avant.
        /// </summary>
        internal static string DocumentSpec_Front {
            get {
                return ResourceManager.GetString("DocumentSpec_Front", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face avant-gauche.
        /// </summary>
        internal static string DocumentSpec_FrontLeft {
            get {
                return ResourceManager.GetString("DocumentSpec_FrontLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Face avant-droite.
        /// </summary>
        internal static string DocumentSpec_FrontRight {
            get {
                return ResourceManager.GetString("DocumentSpec_FrontRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Intérieur.
        /// </summary>
        internal static string DocumentSpec_Interior {
            get {
                return ResourceManager.GetString("DocumentSpec_Interior", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latéral gauche.
        /// </summary>
        internal static string DocumentSpec_LateralLeft {
            get {
                return ResourceManager.GetString("DocumentSpec_LateralLeft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Latéral droit.
        /// </summary>
        internal static string DocumentSpec_LateralRight {
            get {
                return ResourceManager.GetString("DocumentSpec_LateralRight", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Engagement de virement bancaire.
        /// </summary>
        internal static string DocumentType_BankTransferCommitment {
            get {
                return ResourceManager.GetString("DocumentType_BankTransferCommitment", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SimulationClient.
        /// </summary>
        internal static string DocumentType_BookingSimulation {
            get {
                return ResourceManager.GetString("DocumentType_BookingSimulation", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to CIN (recto verso).
        /// </summary>
        internal static string DocumentType_CustomerCIN {
            get {
                return ResourceManager.GetString("DocumentType_CustomerCIN", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Status.
        /// </summary>
        internal static string DocumentType_CustomerCompanyStatus {
            get {
                return ResourceManager.GetString("DocumentType_CustomerCompanyStatus", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retrait.
        /// </summary>
        internal static string DocumentType_CustomerCompanyWithdrawal {
            get {
                return ResourceManager.GetString("DocumentType_CustomerCompanyWithdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to RC.
        /// </summary>
        internal static string DocumentType_CustomerRC {
            get {
                return ResourceManager.GetString("DocumentType_CustomerRC", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiche de livraison.
        /// </summary>
        internal static string DocumentType_DeliveryForm {
            get {
                return ResourceManager.GetString("DocumentType_DeliveryForm", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Rapport d’expertise.
        /// </summary>
        internal static string DocumentType_ExpertiseSheet {
            get {
                return ResourceManager.GetString("DocumentType_ExpertiseSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bordereaux d&apos;achat (BA).
        /// </summary>
        internal static string DocumentType_PurchaseInvoice {
            get {
                return ResourceManager.GetString("DocumentType_PurchaseInvoice", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bon de commande.
        /// </summary>
        internal static string DocumentType_PurchaseOrder {
            get {
                return ResourceManager.GetString("DocumentType_PurchaseOrder", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bon d&apos;aquisition.
        /// </summary>
        internal static string DocumentType_PurchaseVoucher {
            get {
                return ResourceManager.GetString("DocumentType_PurchaseVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fiche d&apos;estimation de reprise.
        /// </summary>
        internal static string DocumentType_QuotationSheet {
            get {
                return ResourceManager.GetString("DocumentType_QuotationSheet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Proposition commerciale.
        /// </summary>
        internal static string DocumentType_SaleProforma {
            get {
                return ResourceManager.GetString("DocumentType_SaleProforma", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bon de reprise.
        /// </summary>
        internal static string DocumentType_TradeInVoucher {
            get {
                return ResourceManager.GetString("DocumentType_TradeInVoucher", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to PV de transfer.
        /// </summary>
        internal static string DocumentType_TransferPV {
            get {
                return ResourceManager.GetString("DocumentType_TransferPV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document de certification.
        /// </summary>
        internal static string DocumentType_VehicleCertificate {
            get {
                return ResourceManager.GetString("DocumentType_VehicleCertificate", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos d&apos;expertise technique.
        /// </summary>
        internal static string DocumentType_VehicleCheckPartImage {
            get {
                return ResourceManager.GetString("DocumentType_VehicleCheckPartImage", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carte grise (recto verso).
        /// </summary>
        internal static string DocumentType_VehicleGrayCard {
            get {
                return ResourceManager.GetString("DocumentType_VehicleGrayCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Photos guidées.
        /// </summary>
        internal static string DocumentType_VehiclePicture {
            get {
                return ResourceManager.GetString("DocumentType_VehiclePicture", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Procuration.
        /// </summary>
        internal static string DocumentType_VehiclePowerOfAttorney {
            get {
                return ResourceManager.GetString("DocumentType_VehiclePowerOfAttorney", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vignette.
        /// </summary>
        internal static string DocumentType_VehicleRoadTax {
            get {
                return ResourceManager.GetString("DocumentType_VehicleRoadTax", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Visite technique.
        /// </summary>
        internal static string DocumentType_VehicleTechnicalVisit {
            get {
                return ResourceManager.GetString("DocumentType_VehicleTechnicalVisit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Document de garantie.
        /// </summary>
        internal static string DocumentType_VehicleWarranty {
            get {
                return ResourceManager.GetString("DocumentType_VehicleWarranty", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Main levée.
        /// </summary>
        internal static string DocumentType_VehicleWithdrawal {
            get {
                return ResourceManager.GetString("DocumentType_VehicleWithdrawal", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Automatique.
        /// </summary>
        internal static string GearType_Automatic {
            get {
                return ResourceManager.GetString("GearType_Automatic", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Manuelle.
        /// </summary>
        internal static string GearType_Manual {
            get {
                return ResourceManager.GetString("GearType_Manual", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Transfére bancaire.
        /// </summary>
        internal static string PaymentMethod_BankTransfer {
            get {
                return ResourceManager.GetString("PaymentMethod_BankTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Espèces.
        /// </summary>
        internal static string PaymentMethod_Cash {
            get {
                return ResourceManager.GetString("PaymentMethod_Cash", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Chèque.
        /// </summary>
        internal static string PaymentMethod_Checks {
            get {
                return ResourceManager.GetString("PaymentMethod_Checks", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Carte bleu.
        /// </summary>
        internal static string PaymentMethod_CreditCard {
            get {
                return ResourceManager.GetString("PaymentMethod_CreditCard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Acompte.
        /// </summary>
        internal static string PaymentType_Direct {
            get {
                return ResourceManager.GetString("PaymentType_Direct", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Crédit.
        /// </summary>
        internal static string PaymentType_Financing {
            get {
                return ResourceManager.GetString("PaymentType_Financing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En attente Expertise.
        /// </summary>
        internal static string TechnicalExpertiseStatusType_Draft {
            get {
                return ResourceManager.GetString("TechnicalExpertiseStatusType_Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modifications en cours.
        /// </summary>
        internal static string TechnicalExpertiseStatusType_PendingEdits {
            get {
                return ResourceManager.GetString("TechnicalExpertiseStatusType_PendingEdits", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Validé.
        /// </summary>
        internal static string TechnicalExpertiseStatusType_QuotationAccepted {
            get {
                return ResourceManager.GetString("TechnicalExpertiseStatusType_QuotationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Rejeté.
        /// </summary>
        internal static string TechnicalExpertiseStatusType_QuotationRejected {
            get {
                return ResourceManager.GetString("TechnicalExpertiseStatusType_QuotationRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation Soumise.
        /// </summary>
        internal static string TechnicalExpertiseStatusType_QuotationSubmitted {
            get {
                return ResourceManager.GetString("TechnicalExpertiseStatusType_QuotationSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Soumise.
        /// </summary>
        internal static string TechnicalExpertiseStatusType_Submitted {
            get {
                return ResourceManager.GetString("TechnicalExpertiseStatusType_Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Récéption confirmée.
        /// </summary>
        internal static string TransferOrderStatusType_Received {
            get {
                return ResourceManager.GetString("TransferOrderStatusType_Received", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Récéption refusée.
        /// </summary>
        internal static string TransferOrderStatusType_ReceivedRejected {
            get {
                return ResourceManager.GetString("TransferOrderStatusType_ReceivedRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En convoie.
        /// </summary>
        internal static string TransferOrderStatusType_Sent {
            get {
                return ResourceManager.GetString("TransferOrderStatusType_Sent", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande de transfer rejeté.
        /// </summary>
        internal static string TransferOrderStatusType_SentRejected {
            get {
                return ResourceManager.GetString("TransferOrderStatusType_SentRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande soumise.
        /// </summary>
        internal static string TransferOrderStatusType_Submitted {
            get {
                return ResourceManager.GetString("TransferOrderStatusType_Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Coupé / Cabriolet.
        /// </summary>
        internal static string VehicleBodyStyle_Cabriolet {
            get {
                return ResourceManager.GetString("VehicleBodyStyle_Cabriolet", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Citadine.
        /// </summary>
        internal static string VehicleBodyStyle_Citadine {
            get {
                return ResourceManager.GetString("VehicleBodyStyle_Citadine", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Compacte.
        /// </summary>
        internal static string VehicleBodyStyle_Compact {
            get {
                return ResourceManager.GetString("VehicleBodyStyle_Compact", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourgonnette.
        /// </summary>
        internal static string VehicleBodyStyle_Fourgonnette {
            get {
                return ResourceManager.GetString("VehicleBodyStyle_Fourgonnette", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Fourgon / Minibus.
        /// </summary>
        internal static string VehicleBodyStyle_MiniVan {
            get {
                return ResourceManager.GetString("VehicleBodyStyle_MiniVan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Pick-up.
        /// </summary>
        internal static string VehicleBodyStyle_Pickup {
            get {
                return ResourceManager.GetString("VehicleBodyStyle_Pickup", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Berline.
        /// </summary>
        internal static string VehicleBodyStyle_Sedan {
            get {
                return ResourceManager.GetString("VehicleBodyStyle_Sedan", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Sportive.
        /// </summary>
        internal static string VehicleBodyStyle_SportsCar {
            get {
                return ResourceManager.GetString("VehicleBodyStyle_SportsCar", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to SUV / 4x4.
        /// </summary>
        internal static string VehicleBodyStyle_SUV {
            get {
                return ResourceManager.GetString("VehicleBodyStyle_SUV", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Monospace.
        /// </summary>
        internal static string VehicleBodyStyle_Wagon {
            get {
                return ResourceManager.GetString("VehicleBodyStyle_Wagon", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offre accéptée.
        /// </summary>
        internal static string VehicleBookingStatusType_Accepted {
            get {
                return ResourceManager.GetString("VehicleBookingStatusType_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande facturée.
        /// </summary>
        internal static string VehicleBookingStatusType_Billed {
            get {
                return ResourceManager.GetString("VehicleBookingStatusType_Billed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande annulée.
        /// </summary>
        internal static string VehicleBookingStatusType_Cancelled {
            get {
                return ResourceManager.GetString("VehicleBookingStatusType_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Véhicule livré.
        /// </summary>
        internal static string VehicleBookingStatusType_Delivered {
            get {
                return ResourceManager.GetString("VehicleBookingStatusType_Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Négociation validée.
        /// </summary>
        internal static string VehicleBookingStatusType_NewPriceAccepted {
            get {
                return ResourceManager.GetString("VehicleBookingStatusType_NewPriceAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Négociation rejetée.
        /// </summary>
        internal static string VehicleBookingStatusType_NewPriceRejected {
            get {
                return ResourceManager.GetString("VehicleBookingStatusType_NewPriceRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En négociation.
        /// </summary>
        internal static string VehicleBookingStatusType_NewPriceSubmitted {
            get {
                return ResourceManager.GetString("VehicleBookingStatusType_NewPriceSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails de payement soumis.
        /// </summary>
        internal static string VehicleBookingStatusType_PayementDetailsSubmitted {
            get {
                return ResourceManager.GetString("VehicleBookingStatusType_PayementDetailsSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offre rejetée.
        /// </summary>
        internal static string VehicleBookingStatusType_Rejected {
            get {
                return ResourceManager.GetString("VehicleBookingStatusType_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande soumise.
        /// </summary>
        internal static string VehicleBookingStatusType_Submitted {
            get {
                return ResourceManager.GetString("VehicleBookingStatusType_Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Bien.
        /// </summary>
        internal static string VehicleCheckPartAction_None {
            get {
                return ResourceManager.GetString("VehicleCheckPartAction_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to ND.
        /// </summary>
        internal static string VehicleCheckPartAction_NotAvailable {
            get {
                return ResourceManager.GetString("VehicleCheckPartAction_NotAvailable", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A réparer.
        /// </summary>
        internal static string VehicleCheckPartAction_Repair {
            get {
                return ResourceManager.GetString("VehicleCheckPartAction_Repair", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A remplacer.
        /// </summary>
        internal static string VehicleCheckPartAction_Replacement {
            get {
                return ResourceManager.GetString("VehicleCheckPartAction_Replacement", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to  - .
        /// </summary>
        internal static string VehicleCheckPartType_None {
            get {
                return ResourceManager.GetString("VehicleCheckPartType_None", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Modification en cours.
        /// </summary>
        internal static string VehicleCheckPartType_PendingEdit {
            get {
                return ResourceManager.GetString("VehicleCheckPartType_PendingEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Neuf.
        /// </summary>
        internal static string VehicleCondition_New {
            get {
                return ResourceManager.GetString("VehicleCondition_New", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Occasion.
        /// </summary>
        internal static string VehicleCondition_Used {
            get {
                return ResourceManager.GetString("VehicleCondition_Used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Diesel.
        /// </summary>
        internal static string VehicleFuelType_Diesel {
            get {
                return ResourceManager.GetString("VehicleFuelType_Diesel", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eléctrique.
        /// </summary>
        internal static string VehicleFuelType_Electric {
            get {
                return ResourceManager.GetString("VehicleFuelType_Electric", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Essence.
        /// </summary>
        internal static string VehicleFuelType_Gasoline {
            get {
                return ResourceManager.GetString("VehicleFuelType_Gasoline", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Hybride.
        /// </summary>
        internal static string VehicleFuelType_Hybrid {
            get {
                return ResourceManager.GetString("VehicleFuelType_Hybrid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achat.
        /// </summary>
        internal static string VehicleOrigin_Purchase {
            get {
                return ResourceManager.GetString("VehicleOrigin_Purchase", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprise.
        /// </summary>
        internal static string VehicleOrigin_TradeIn {
            get {
                return ResourceManager.GetString("VehicleOrigin_TradeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Eligible.
        /// </summary>
        internal static string VehiclePurchaseStatusType_Accepted {
            get {
                return ResourceManager.GetString("VehiclePurchaseStatusType_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande facturée.
        /// </summary>
        internal static string VehiclePurchaseStatusType_Billed {
            get {
                return ResourceManager.GetString("VehiclePurchaseStatusType_Billed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande concrétisée.
        /// </summary>
        internal static string VehiclePurchaseStatusType_Complete {
            get {
                return ResourceManager.GetString("VehiclePurchaseStatusType_Complete", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offre acceptée.
        /// </summary>
        internal static string VehiclePurchaseStatusType_CustomerAccepted {
            get {
                return ResourceManager.GetString("VehiclePurchaseStatusType_CustomerAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande de forçage.
        /// </summary>
        internal static string VehiclePurchaseStatusType_CustomerNegociated {
            get {
                return ResourceManager.GetString("VehiclePurchaseStatusType_CustomerNegociated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offre rejetée.
        /// </summary>
        internal static string VehiclePurchaseStatusType_CustomerRejected {
            get {
                return ResourceManager.GetString("VehiclePurchaseStatusType_CustomerRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande désactivée.
        /// </summary>
        internal static string VehiclePurchaseStatusType_Deactivated {
            get {
                return ResourceManager.GetString("VehiclePurchaseStatusType_Deactivated", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents acceptés.
        /// </summary>
        internal static string VehiclePurchaseStatusType_DocumentsAccepted {
            get {
                return ResourceManager.GetString("VehiclePurchaseStatusType_DocumentsAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents conformes.
        /// </summary>
        internal static string VehiclePurchaseStatusType_DocumentsConformityAccepted {
            get {
                return ResourceManager.GetString("VehiclePurchaseStatusType_DocumentsConformityAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents non conformes.
        /// </summary>
        internal static string VehiclePurchaseStatusType_DocumentsConformityRejected {
            get {
                return ResourceManager.GetString("VehiclePurchaseStatusType_DocumentsConformityRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents rejetés.
        /// </summary>
        internal static string VehiclePurchaseStatusType_DocumentsRejected {
            get {
                return ResourceManager.GetString("VehiclePurchaseStatusType_DocumentsRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Documents chargés.
        /// </summary>
        internal static string VehiclePurchaseStatusType_DocumentsSubmited {
            get {
                return ResourceManager.GetString("VehiclePurchaseStatusType_DocumentsSubmited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation acceptée.
        /// </summary>
        internal static string VehiclePurchaseStatusType_QuotationAccepted {
            get {
                return ResourceManager.GetString("VehiclePurchaseStatusType_QuotationAccepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Quotation rejetée.
        /// </summary>
        internal static string VehiclePurchaseStatusType_QuotationRejected {
            get {
                return ResourceManager.GetString("VehiclePurchaseStatusType_QuotationRejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Non Eligible.
        /// </summary>
        internal static string VehiclePurchaseStatusType_Rejected {
            get {
                return ResourceManager.GetString("VehiclePurchaseStatusType_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Nouvelle demande.
        /// </summary>
        internal static string VehiclePurchaseStatusType_Submited {
            get {
                return ResourceManager.GetString("VehiclePurchaseStatusType_Submited", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Retour Expertise.
        /// </summary>
        internal static string VehiclePurchaseStatusType_TechnicalExpertisePendingEdit {
            get {
                return ResourceManager.GetString("VehiclePurchaseStatusType_TechnicalExpertisePendingEdit", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande expertisé.
        /// </summary>
        internal static string VehiclePurchaseStatusType_TechnicalExpertiseSubmitted {
            get {
                return ResourceManager.GetString("VehiclePurchaseStatusType_TechnicalExpertiseSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Achat.
        /// </summary>
        internal static string VehiclePurchaseType_Standard {
            get {
                return ResourceManager.GetString("VehiclePurchaseType_Standard", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Reprise.
        /// </summary>
        internal static string VehiclePurchaseType_TradeIn {
            get {
                return ResourceManager.GetString("VehiclePurchaseType_TradeIn", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Étranger.
        /// </summary>
        internal static string VehicleRegistrationType_Foreign {
            get {
                return ResourceManager.GetString("VehicleRegistrationType_Foreign", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Maroc.
        /// </summary>
        internal static string VehicleRegistrationType_Local {
            get {
                return ResourceManager.GetString("VehicleRegistrationType_Local", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offre accéptée.
        /// </summary>
        internal static string VehicleSaleStatusType_Accepted {
            get {
                return ResourceManager.GetString("VehicleSaleStatusType_Accepted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande afféctée .
        /// </summary>
        internal static string VehicleSaleStatusType_Assigned {
            get {
                return ResourceManager.GetString("VehicleSaleStatusType_Assigned", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande facturée.
        /// </summary>
        internal static string VehicleSaleStatusType_Billed {
            get {
                return ResourceManager.GetString("VehicleSaleStatusType_Billed", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande annulée.
        /// </summary>
        internal static string VehicleSaleStatusType_Cancelled {
            get {
                return ResourceManager.GetString("VehicleSaleStatusType_Cancelled", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Véhicule(s) livré.
        /// </summary>
        internal static string VehicleSaleStatusType_Delivered {
            get {
                return ResourceManager.GetString("VehicleSaleStatusType_Delivered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Détails de paiements soumis.
        /// </summary>
        internal static string VehicleSaleStatusType_PriceSubmitted {
            get {
                return ResourceManager.GetString("VehicleSaleStatusType_PriceSubmitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Offre rejetée.
        /// </summary>
        internal static string VehicleSaleStatusType_Rejected {
            get {
                return ResourceManager.GetString("VehicleSaleStatusType_Rejected", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Demande soumise.
        /// </summary>
        internal static string VehicleSaleStatusType_Submitted {
            get {
                return ResourceManager.GetString("VehicleSaleStatusType_Submitted", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Stock Brut.
        /// </summary>
        internal static string VehicleStatusType_Active {
            get {
                return ResourceManager.GetString("VehicleStatusType_Active", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Réservé.
        /// </summary>
        internal static string VehicleStatusType_Booked {
            get {
                return ResourceManager.GetString("VehicleStatusType_Booked", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En traitement de demande.
        /// </summary>
        internal static string VehicleStatusType_Draft {
            get {
                return ResourceManager.GetString("VehicleStatusType_Draft", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En convoie.
        /// </summary>
        internal static string VehicleStatusType_InTransfer {
            get {
                return ResourceManager.GetString("VehicleStatusType_InTransfer", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to En attente Expertise.
        /// </summary>
        internal static string VehicleStatusType_Pending {
            get {
                return ResourceManager.GetString("VehicleStatusType_Pending", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Publié.
        /// </summary>
        internal static string VehicleStatusType_Published {
            get {
                return ResourceManager.GetString("VehicleStatusType_Published", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-Résérvé.
        /// </summary>
        internal static string VehicleStatusType_Reserved {
            get {
                return ResourceManager.GetString("VehicleStatusType_Reserved", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Vendu.
        /// </summary>
        internal static string VehicleStatusType_Sold {
            get {
                return ResourceManager.GetString("VehicleStatusType_Sold", resourceCulture);
            }
        }
    }
}
