using System.Collections.Generic;
using P = ACG.ONP.SIM.Domain.Constants.AuthorizationConstants.Permissions;

namespace ACG.ONP.SIM.Domain.Constants
{
    public static class SeedData
    {
        public static List<string> Cities = new List<string>
        {
            "Afourar",
            "Agadir",
            "Ait Melloul",
            "Al Hoceima",
            "Amizmiz",
            "Aourir",
            "Assila",
            "Azemmour",
            "Azilal",
            "Azrou",
            "Aït Baha",
            "Bejaâd",
            "Ben Ahmed",
            "Benguerir",
            "Benslimane",
            "Berkane",
            "Berrechid",
            "Bin Elouidane",
            "Bni Ansar",
            "Bouarfa",
            "Boujdour",
            "Bouknadel",
            "Boulemane",
            "Bouznika",
            "Béni Mellal",
            "Casablanca",
            "Chefchaouen",
            "Chichaoua",
            "Dakhla",
            "Demnate",
            "El Borouj",
            "El Gara",
            "El Hajeb",
            "El Jadida",
            "El Kelaâ des Sraghna",
            "Erfoud",
            "Errachidia",
            "Es-Semara",
            "Essaouira",
            "Figuig",
            "Fkih Ben Salah",
            "Fnideq",
            "Fès",
            "Guelmim",
            "Guercif",
            "Had Kourt",
            "Harhoura",
            "Ifrane",
            "Imintanoute",
            "Imouzzer Kandar",
            "Jerada",
            "Jorf Lasfar",
            "Kasba Tadla",
            "Kelaat-M'Gouna",
            "Khemis Zemamra",
            "Khouribga",
            "Khémisset",
            "Khénifra",
            "Ksar El Kebir",
            "Kénitra",
            "Laayoune",
            "Lagouira",
            "Larache",
            "M'dik",
            "M'rirt",
            "Marrakech",
            "Martil",
            "Mehdia",
            "Meknès",
            "Midelt",
            "Missour",
            "Mohammedia",
            "Moulay Bousselham",
            "Moulay Yaâcoub",
            "Mzouda",
            "Nador",
            "Ouarzazate",
            "Ouazzane",
            "Oued Laou",
            "Oued Zem",
            "Ouezzane",
            "Oujda",
            "Rabat",
            "Ras El Aïn",
            "Rissani",
            "Rommani",
            "Safi",
            "Salé",
            "Saïdia",
            "Sefrou",
            "Settat",
            "Sidi Allal El Bahraoui",
            "Sidi Bennour",
            "Sidi Ifni",
            "Sidi Kacem",
            "Sidi Slimane",
            "Sidi Taibi",
            "Sidi Yahya El Gharb",
            "Sidi Yahya Ou Saad",
            "Sidi Yahya Ou Youssef",
            "Skhirat",
            "Souk El Arbaa",
            "Tafraout",
            "Taghazout",
            "Tan-Tan",
            "Tanger",
            "Taounate",
            "Tarfaya",
            "Taroudant",
            "Tata",
            "Taza",
            "Tiflet",
            "Tit Mellil",
            "Tiznit",
            "Témara",
            "Tétouan",
            "Zagora"
        };


        public static Dictionary<string, List<string>> RolePermissions = new Dictionary<string, List<string>>();
    }
}