namespace ACG.ONP.SIM.Domain.Enums
{
    public enum DocumentSpec
    {
        None = 0,
        AutoGenerated,
        Front,
        FrontLeft,
        FrontRight,
        Back,
        BackLeft,
        BackRight,
        Dashboard,
        Interior,
        LateralRight,
        LateralLeft,
        PaperWork // need to differenciate vehicle purchase documents needed to validate and those generated after validation
    }
}